// Seed exercise definitions — the movement library written to the vault on
// first run.
//
// These are written to the vault on first run so the user has something to pick
// from. Once the files exist, this data is no longer consulted — the user's
// copies in the vault are the source of truth and can be edited freely.
//
// Conventions:
//   - primaryMuscles: muscles receiving direct training stimulus (1x volume credit)
//   - secondaryMuscles: muscles worked meaningfully but not the main target (0.5x credit)
//   - bodyweight: true means volume tracking can skip it (per project decision)
//   - progression: "double" = 3-8 rep double progression; "linear" = add weight
//     each session (heavy compounds); "none" = time/ holds that don't fit either.
//   - order: position within the day's menu. Numbered 1..N per rotation slot;
//     collisions across slots don't matter because the menu filters by slot
//     before sorting. Anything not on a planned day carries
//     DEFAULT_EXERCISE_ORDER so it sinks to the bottom if ever re-enabled.
//   - targetSets: sets the plan calls for. 4 on the delt/tricep/chest work,
//     3 on the heavy compounds and the leg/pulling machines.
//
// The three planned days (Astartes Triptych — push/pull/legs), with each
// movement's set prescription:
//
//   Push  (6 exercises, 23 sets)      Pull  (6 exercises, 20 sets)
//     1 Bench Press               4     1 Deadlift                    4
//     2 Shoulder Press            4     2 Seated Cable Row            3
//     3 Dips (assisted)           4     3 Bent-Over DB Row            3
//     4 Lateral Raises            4     4 Lat Pulldown                3
//     5 Tricep Pushdown           4     5 Face Pull / Rev. Pec Deck   4
//     6 DB Wrist Curl & Ext.      3     6 Bicep Curl (Cable)          3
//   Legs  (5 exercises, 16 sets)
//     2 Shoulder Press   4     5 Leg Extension    3
//     3 Leg Press        3     6 Sit-ups          3
//     4 Leg Curl         3
//
// Shoulder Press sits on BOTH push and legs. `order` is one number per
// exercise, not per slot, so its position (2) has to serve both days — it
// opens leg day and sits second on push. Squat, Hanging Leg Raise and
// Pallof Press came off leg day; Pull-ups and the seated bicep curl came
// off pull day. All of them keep their files and their logged history, and
// stay reachable via "Other exercise".
//
// Movements that used to sit on a push/pull/legs day but aren't on the plan
// keep their files (and therefore their logged history and volume credit) —
// they just carry no push/pull/legs slot, so the Ritual menu never offers
// them. Re-adding a slot in the vault file brings one back instantly, and
// they stay pickable mid-workout through the Ritual's "Other exercise"
// search — which is how the lifts that used to live on the retired `upper`
// and `lower` days remain reachable.

import type { ExerciseFile } from "../domain/schemas";
import { DEFAULT_EXERCISE_ORDER } from "../domain/schemas";

// Set prescriptions. Isolation and delt/tricep work carries 4; the heavy
// compounds and the pulling/leg machines carry 3.
const SETS_4 = 4;
const SETS_3 = 3;

export const SEED_EXERCISES: ExerciseFile[] = [
  // ------------------------------------------------------------ Push (1..6)
  {
    id: "bench_press",
    displayName: "Bench Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    rotationSlots: ["push"],
    order: 1,
    targetSets: SETS_4,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "overhead_press",
    displayName: "Shoulder Press",
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["triceps", "side_delts"],
    rotationSlots: ["push", "legs"],
    order: 2,
    targetSets: SETS_4,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "dips",
    displayName: "Dips (assisted)",
    // Triceps promoted to primary: a dip drives full elbow extension under
    // load, so the triceps take direct stimulus, not incidental. Leaving
    // them at 0.5x credit under-counted every push day's tricep volume.
    primaryMuscles: ["chest", "triceps"],
    secondaryMuscles: ["front_delts"],
    rotationSlots: ["push"],
    order: 3,
    targetSets: SETS_4,
    equipment: "bodyweight",
    progression: "double",
    bodyweight: true,
    // Assisted: log the weight field as assistance if the machine shows it,
    // or leave it at 0 and let reps carry the progression.
    notes: "Assisted.",
  },
  {
    id: "lateral_raise",
    displayName: "Lateral Raises",
    primaryMuscles: ["side_delts"],
    secondaryMuscles: [],
    rotationSlots: ["push"],
    order: 4,
    targetSets: SETS_4,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "tricep_pushdown",
    displayName: "Tricep Pushdown",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    rotationSlots: ["push"],
    order: 5,
    targetSets: SETS_4,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "db_wrist_curl",
    displayName: "DB Wrist Curl & Extension",
    primaryMuscles: ["forearms"],
    secondaryMuscles: [],
    rotationSlots: ["push"],
    order: 6,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "Curl and extension paired — log the combined set.",
  },

  // ------------------------------------------------------------ Pull (1..7)
  {
    id: "deadlift",
    displayName: "Deadlift",
    // Lower back promoted to primary: the erectors are what hold the spine
    // rigid against the load — the deadlift is the single largest source of
    // lower-back stimulus in this plan, and nothing else on push/pull/legs
    // trains them directly. At 0.5x it was the only lower-back credit the
    // week saw, which read as chronically under-MEV in the Sanctum.
    primaryMuscles: ["hamstrings", "glutes", "back", "lower_back"],
    secondaryMuscles: ["lats", "forearms", "quads"],
    rotationSlots: ["pull"],
    order: 1,
    targetSets: SETS_4,
    equipment: "barbell",
    progression: "linear",
    bodyweight: false,
    notes: "",
  },
  {
    id: "seated_row",
    displayName: "Seated Cable Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["lats", "biceps", "rear_delts"],
    rotationSlots: ["pull"],
    order: 2,
    targetSets: SETS_3,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "bent_over_db_row",
    displayName: "Bent-Over Dumbbell Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["lats", "biceps", "rear_delts"],
    rotationSlots: ["pull"],
    order: 3,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "pullup",
    displayName: "Pull-ups (assisted)",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["back", "biceps"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "bodyweight",
    progression: "double",
    bodyweight: true,
    notes: "Assisted.",
  },
  {
    id: "lat_pulldown",
    displayName: "Lat Pulldown",
    primaryMuscles: ["lats"],
    secondaryMuscles: ["back", "biceps"],
    rotationSlots: ["pull"],
    order: 4,
    targetSets: SETS_3,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "face_pull",
    displayName: "Face Pull / Reverse Pec Deck",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    rotationSlots: ["pull"],
    order: 5,
    targetSets: SETS_4,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    // One slot, either movement — they hit the same muscle and the history
    // is more useful pooled than split across two near-identical entries.
    notes: "Face pull or reverse pec deck — whichever machine is free.",
  },
  {
    id: "cable_curl",
    displayName: "Bicep Curl (Cable)",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    rotationSlots: ["pull"],
    order: 6,
    targetSets: SETS_3,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "seated_curl",
    displayName: "Bicep Curl (Seated)",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },

  // ------------------------------------------------------------ Legs (1..6)
  {
    id: "back_squat",
    displayName: "Squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "hamstrings", "lower_back"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "linear",
    bodyweight: false,
    notes: "",
  },
  {
    id: "leg_press",
    displayName: "Leg Press",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "hamstrings"],
    rotationSlots: ["legs"],
    order: 3,
    targetSets: SETS_3,
    equipment: "machine",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "leg_curl",
    displayName: "Leg Curl",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: [],
    rotationSlots: ["legs"],
    order: 4,
    targetSets: SETS_3,
    equipment: "machine",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "leg_extension",
    displayName: "Leg Extension",
    primaryMuscles: ["quads"],
    secondaryMuscles: [],
    rotationSlots: ["legs"],
    order: 5,
    targetSets: SETS_3,
    equipment: "machine",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "hanging_leg_raise",
    displayName: "Hanging Leg Raise",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques", "forearms"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "bodyweight",
    progression: "double",
    bodyweight: true,
    notes: "",
  },
  {
    id: "pallof_press",
    displayName: "Pallof Press",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["abs"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    notes: "Anti-rotation. Log one set per side.",
  },

  {
    id: "situps",
    displayName: "Sit-ups",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques"],
    rotationSlots: ["legs"],
    order: 6,
    targetSets: SETS_3,
    equipment: "bodyweight",
    progression: "double",
    bodyweight: true,
    notes: "",
  },

  // ----------------------------------------------------- Off-plan: no slot
  //
  // These carried `upper` or `lower` before the rotation narrowed to three
  // days. They keep their definitions (and every set ever logged against
  // them) and are reachable from "Other exercise" during any workout.
  {
    id: "rear_delt_fly",
    displayName: "Rear Delt Fly",
    primaryMuscles: ["rear_delts"],
    secondaryMuscles: ["back"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "incline_curl",
    displayName: "Incline Dumbbell Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: [],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "preacher_curl",
    displayName: "Preacher Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "overhead_tricep_extension",
    displayName: "Overhead Tricep Extension",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "skull_crusher",
    displayName: "Skull Crusher",
    primaryMuscles: ["triceps"],
    secondaryMuscles: [],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "arnold_press",
    displayName: "Arnold Press",
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["side_delts", "triceps"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "barbell_shrug",
    displayName: "Barbell Shrug",
    primaryMuscles: ["back"],
    secondaryMuscles: ["forearms"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "rdl",
    displayName: "Romanian Deadlift",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "lower_back"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "hip_thrust",
    displayName: "Hip Thrust",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "good_morning",
    displayName: "Good Morning",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["lower_back", "glutes"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "single_leg_rdl",
    displayName: "Single-Leg RDL",
    primaryMuscles: ["hamstrings"],
    secondaryMuscles: ["glutes", "lower_back"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "kettlebell_swing",
    displayName: "Kettlebell Swing",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings", "lower_back"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "kettlebell",
    progression: "linear",
    bodyweight: false,
    notes: "",
  },
  {
    id: "plank",
    displayName: "Plank",
    primaryMuscles: ["abs"],
    secondaryMuscles: ["obliques", "lower_back"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "bodyweight",
    progression: "none",
    bodyweight: true,
    notes: "Time-based — log reps field as hold seconds.",
  },
  {
    id: "russian_twist",
    displayName: "Russian Twist",
    primaryMuscles: ["obliques"],
    secondaryMuscles: ["abs"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "linear",
    bodyweight: false,
    notes: "",
  },

  // ------------------------------------------------------------- Off-plan
  //
  // No rotation slot: these never appear in the Ritual menu, but the files
  // (and every set ever logged against them) stay intact. Add a slot back to
  // the vault file to bring one out of retirement.
  {
    id: "incline_db_press",
    displayName: "Incline Dumbbell Press",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts", "triceps"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "seated_db_press",
    displayName: "Seated Dumbbell Shoulder Press",
    primaryMuscles: ["front_delts"],
    secondaryMuscles: ["side_delts", "triceps"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "pushups",
    displayName: "Push-ups",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["triceps", "front_delts"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "bodyweight",
    progression: "double",
    bodyweight: true,
    notes: "",
  },
  {
    id: "close_grip_bench",
    displayName: "Close-Grip Bench Press",
    primaryMuscles: ["triceps"],
    secondaryMuscles: ["chest", "front_delts"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "cable_fly",
    displayName: "Cable Fly",
    primaryMuscles: ["chest"],
    secondaryMuscles: ["front_delts"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "cable",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "barbell_row",
    displayName: "Barbell Row",
    primaryMuscles: ["back"],
    secondaryMuscles: ["lats", "biceps", "rear_delts"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "barbell_curl",
    displayName: "Barbell Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "hammer_curl",
    displayName: "Hammer Curl",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "front_squat",
    displayName: "Front Squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "abs"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "barbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "bulgarian_split_squat",
    displayName: "Bulgarian Split Squat",
    primaryMuscles: ["quads"],
    secondaryMuscles: ["glutes", "hamstrings"],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "dumbbell",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "standing_calf_raise",
    displayName: "Standing Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "machine",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
  {
    id: "seated_calf_raise",
    displayName: "Seated Calf Raise",
    primaryMuscles: ["calves"],
    secondaryMuscles: [],
    rotationSlots: [],
    order: DEFAULT_EXERCISE_ORDER,
    targetSets: SETS_3,
    equipment: "machine",
    progression: "double",
    bodyweight: false,
    notes: "",
  },
];
